version: '3'

networks:
  grafana:

services:
  grafana:
    image: grafana/grafana:9.2.1
    container_name: grafana
    ports:
      - 3000:3000
    networks:
      - grafana
    volumes:
      - ./grafana/data:/var/lib/grafana
      - ./grafana/etc:/etc/grafana/  
        
    environment:
      - GF_PATHS_CONFIG=/etc/grafana/grafana.ini
    user: "1000"    

  loki:
    image: grafana/loki:2.6.1
    container_name: loki
    ports:
      - 3100:3100
    networks:
      - grafana
    volumes:
      - ./loki:/mnt/config
    command: -config.file=/mnt/config/loki.yaml

  promtail-ext:
    image: grafana/promtail:2.6.1
    container_name: promtail-ext    
    volumes:
      - ./promtail-ext/logs:/var/log
      - ./promtail-ext/etc:/etc/promtail
    command: -config.file=/etc/promtail/promtail.yml
    networks:
      - grafana

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - 9090:9090
    networks:
      - grafana
    volumes:
      - ./prometheus:/etc/prometheus

  hana:
    image: hana:latest
    container_name: hana01
    hostname: hana01
    privileged: true
    networks:
      - grafana
    volumes:
      - ./hana/DATA_UNITS/HDB_SERVER_LINUX_X86_64:/src
      - ./hana/promtail/etc:/etc/promtail
    deploy:
      resources:
        limits:
          cpus: '2.5'
          memory: 14336M
    command:
      - /bin/bash
      - -c
      - |
        cd /src && cat templateFile.xml | ./hdblcm --action=install --ignore=check_min_mem -b --configfile=templateFile --read_password_from_stdin=xml
        promtail-linux-amd64 -config.file=/etc/promtail/promtail.yml &
        node_exporter
        
